function plot_virtualgauge (file, option)
% This script is used to the location and numbering of virtual tsunami 
% gauges in ts_location.dat;
% file: 
%       ts_location.dat, or other xy coordinate file;
% option:
%       = 0: do not add gauge number;
%       = 1: add gauge number, align horizontally;
%       = 2: add gauge number, align based on orientations of its neighbors;
%       = 3: add gauge number every 5 gauges, align based on orientations of its neighbors;

hold on
ts_loc = load(file);

n_loc = length(ts_loc(:,1));

% mark virtual gauge locations
plot(ts_loc(:,1),ts_loc(:,2),'r.')
% plot(ts_loc(:,1),ts_loc(:,2),'ko')

% add virtual gauge numbers;
if option == 1
    for k = 1:n_loc
        text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
            'HorizontalAlignment','left',...
            'VerticalAlignment','middle');
    end
end
if option == 2
    for k = 1:n_loc
        if n_loc <= 2
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                    'HorizontalAlignment','right',...
                    'VerticalAlignment','middle',...
                    'FontSize',5);            
        else
            if k<n_loc
                ds = sqrt((ts_loc(k+1,1)-ts_loc(k,1))^2+...
                            (ts_loc(k+1,2)-ts_loc(k,2))^2);
                sn = (ts_loc(k+1,2)-ts_loc(k,2))/ds;
                cs = (ts_loc(k+1,1)-ts_loc(k,1))/ds;
                if sn>=0.0 & cs>=0.0
                    ang = asind(sn);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle',...
                        'Rotation',ang-90.0,...
                        'FontSize',5)
                elseif sn>=0.0 & cs<=0.0
                    ang = acosd(cs);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle',...
                        'Rotation',ang-90.0,...
                        'FontSize',5)  
                elseif sn<0.0 & cs<=0.0
                    ang = asind(sn);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','middle',...
                        'Rotation',90.0-ang+180.0,...
                        'FontSize',5)
                elseif sn<0.0 & cs>=0.0
                    ang = asind(sn);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle',...
                        'Rotation',ang-90.0+180.0,...
                        'FontSize',5)                     
                end
            else
                text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                    'HorizontalAlignment','right',...
                    'VerticalAlignment','middle',...
                    'FontSize',5)
            end
        end
            
    end
end

if option == 3
    for k = 1:n_loc
        if mod(k,5)==1
        if n_loc <= 2
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                    'HorizontalAlignment','right',...
                    'VerticalAlignment','middle');            
        else
            if k<n_loc
                ds = sqrt((ts_loc(k+1,1)-ts_loc(k,1))^2+...
                            (ts_loc(k+1,2)-ts_loc(k,2))^2);
                sn = (ts_loc(k+1,2)-ts_loc(k,2))/ds;
                cs = (ts_loc(k+1,1)-ts_loc(k,1))/ds;
                if sn>=0.0 & cs>=0.0
                    ang = asind(sn);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle',...
                        'Rotation',ang-90.0)
                elseif sn>=0.0 & cs<=0.0
                    ang = acosd(cs);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle',...
                        'Rotation',ang-90.0)  
                elseif sn<0.0 & cs<=0.0
                    ang = asind(sn);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','middle',...
                        'Rotation',90.0-ang+180.0)
                elseif sn<0.0 & cs>=0.0
                    ang = asind(sn);
                    text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle',...
                        'Rotation',ang-90.0+180.0)                     
                end
            else
                text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                    'HorizontalAlignment','right',...
                    'VerticalAlignment','middle')
            end
        end
        end    
    end
end

if option == 4
    for k = 1:n_loc
        if mod(k,5)==1
        plot(ts_loc(k,1),ts_loc(k,2),'r+')            
        plot(ts_loc(k,1),ts_loc(k,2),'k.')
        if k==211
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','top','Color','b');
        elseif k==1
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','bottom','Color','b');                    
        elseif k==186
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle','Color','b');
        elseif k==191
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','center',...
                        'VerticalAlignment','top','Color','b');
        elseif k==136
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','center',...
                        'VerticalAlignment','bottom','Color','b');
        elseif k==146
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','middle','Color','b');
        elseif k==121
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','center',...
                        'VerticalAlignment','bottom','Color','b');
        elseif k==126
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','bottom','Color','b');
        elseif k==241
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','right',...
                        'VerticalAlignment','top','Color','b');
        elseif k==141
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','center',...
                        'VerticalAlignment','bottom','Color','b');
        elseif k==181
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','top','Color','b');
        elseif k==151
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','bottom','Color','b');
        elseif k==166
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','middle','Color','b');  
        elseif k==116
            text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                        'HorizontalAlignment','left',...
                        'VerticalAlignment','middle','Color','b');                      
        else
        text(ts_loc(k,1),ts_loc(k,2),num2str(k),...
                    'HorizontalAlignment','left',...
                    'VerticalAlignment','top','Color','b');
        end
        end
    end
end

